apiVersion: apps/v1
kind: Deployment
metadata: #Dictionary
  name: maruti-nextjs
  namespace: dev
spec: # Dictionary
  replicas: 2
  selector:
    matchLabels:
      app: maruti-nextjs
  template:  
    metadata: # Dictionary
      name: maruti-nextjs-pod
      labels: # Dictionary
        app: maruti-nextjs # Key value pairs
    spec:
      containers: # List
        - name: maruti-nextjs-container
          image: 'europe-west2-docker.pkg.dev/fair-melody-396111/mtech/new:V1'  #<image-name:image-version>
          ports: 
            - containerPort: 80  
          env:
            - name: PORT
              value: "80"
          imagePullPolicy: Always
          #fshfkjshfjk
