apiVersion: apps/v1
kind: Deployment
metadata:
  name: maruti-nextjs
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: maruti-nextjs
  template:  
    metadata:
      name: maruti-nextjs
      labels:
        app: maruti-nextjs
    spec:
      containers:
      - name: maruti-nextjs
        image: IMAGE_NAME
        env:
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 1000Mi
        imagePullPolicy: IfNotPresent
