apiVersion: v1
kind: Service
metadata:
  name: maruti-nextjs-lb-service
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: maruti-nextjs
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port   
