steps:
# This step builds the container image.
- name: 'gcr.io/fair-melody-396111/mtech-image'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/fair-melody-396111/myapps-repository/mtech-image:$SHORT_SHA'
  - '.'

# This step pushes the image to Artifact Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/fair-melody-396111/myapps-repository/mtech-image:$SHORT_SHA'
