steps:
  # - name: 'gcr.io/cloud-builders/git'
  #   entrypoint: /bin/bash
  #   args:
  #     - -c
  #     - |
  #       SHORT_SHA=$(git rev-parse --short main)
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'europe-west2-docker.pkg.dev/fair-melody-396111/mtech/new:${SHORT_SHA}', '-f', '.docker/Dockerfile', '.']
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'europe-west2-docker.pkg.dev/fair-melody-396111/mtech/new:${SHORT_SHA}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Authorize Cloud Build'
    entrypoint: 'bash'
    args:
      - -c
      - |
        apt-get install dnsutils -y &&
        cloudbuild_external_ip=$(dig @resolver4.opendns.com myip.opendns.com +short) &&
        gcloud container clusters update cluster-1 --region=europe-west2 --enable-master-authorized-networks --master-authorized-networks $cloudbuild_external_ip/32 &&
        echo $cloudbuild_external_ip 
  - id: 'Setting Nginx Image Tag'
    name: ubuntu
    args: ['bash','-c','sed -i "s,IMAGE_NAME,europe-west2-docker.pkg.dev/fair-melody-396111/mtech/new:V1," .k8s/deployment.yaml']
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
   
    #   && gke-deploy run --filename=.k8s/deployment.yaml --image=europe-west2-docker.pkg.dev/fair-melody-396111/mtech/new:$ne --location=europe-west2 --cluster=cluster-1
    - 'run'
    - '--filename=.k8s/deployment.yaml'
    #- '--image=europe-west2-docker.pkg.dev/fair-melody-396111/mtech/new:V1'
    - '--location=europe-west2'
    - '--cluster=cluster-1'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Remove Authorized IP'
    entrypoint: 'bash'
    args:
      - -c
      - |
        apt-get install dnsutils -y &&
        #maruti_ip=$(61.12.85.170/32) &&
        gcloud container clusters update cluster-1 --region=europe-west2 --enable-master-authorized-networks --master-authorized-networks='61.12.85.170/32','27.109.3.32' 
        #gcloud container clusters update cluster-1 --region=europe-west2 --enable-master-authorized-networks --master-authorized-networks $maruti_ip 
         
        

# # Store images in Google Artifact Registry 
# images:
#   - europe-west2-docker.pkg.dev/fair-melody-396111/mtech/new
 
